export const translations = {
  en: {
    my_decks: 'My Decks',
    study: 'Study',
    stats: 'Statistics',
    your_decks: 'Your Decks',
    add_deck: '+ New Deck',
    manage_cards: 'Manage Cards',
    delete_deck: 'Delete Deck',
    add_card: ' Add Card',
    question: 'Question',
    answer: 'Answer',
    cancel: 'Cancel',
    create: 'Create',
    save: 'Save',
    add: 'Add',
    select_deck: 'Select a deck to add or edit cards',
    choose_deck: 'Choose a deck to study',
    your_stats: 'Your Statistics',
    learned: 'learned',
    no_cards: 'No cards',
    deck_done: 'Deck complete!',
    deck_done_sub: 'Great! You went through all the cards.',
    back: '← Back',
    exit: '← Exit',
    know: 'Know ✓',
    dont_know: "Don't know ✕",
    delete_confirm: 'Delete forever?',
    confirm: 'Confirm',
    create_deck: 'Create New Deck',
    deck_name: 'Deck name',
    deck_desc: 'Description (optional)',
    cards: 'cards',
    deck_complete_btn: 'Deck complete',
    cards_in_deck: 'Cards in deck:',
    learned_count: 'learned',
    cards_count: 'cards',
    no_cards: 'No cards',
    no_cards_in_deck: 'No cards in this deck',
    add_card_btn: '+ Add Card',
    deck_complete_btn: 'Deck complete',
    edit_card_btn: 'Edit Card',
    delete_card_btn: 'Delete Card',
    enter_question_answer: 'Please enter both question and answer',
    study: 'Study',
    account: 'Account',
    hero_title: 'Learn anything faster!',
    hero_sub: 'Create flashcard decks, study at your own pace, and track your progress — all in one place',
    feature_create: 'Create decks',
    feature_study: 'Study & repeat',
    feature_track: 'Track progress',
    auth_title: 'Register to try it out!',
    contact: 'Contact',
    password: 'Password',
    email: 'Email',
    register: 'Register',
    sign_in: 'Sign In',
    continue_google: 'Continue with Google',
    password_length: 'Password must be at least 6 characters',
    email_already_in_use: 'This email is already registered. Try signing in',
    something_went_wrong: 'Something went wrong. Please try again',
    or: 'or',
    enter_emailAndPassword: 'Please enter your email and password',
    incorrect_email_or_password: 'Incorrect email or password',
    valid_emailAndPassword: 'Please enter a valid email address'
  },
  ru: {
    my_decks: 'Мои колоды',
    study: 'Учёба',
    stats: 'Статистика',
    your_decks: 'Ваши колоды',
    add_deck: '+ Новая колода',
    manage_cards: 'Управление карточками',
    delete_deck: 'Удалить колоду',
    add_card: 'Добавить карточку',
    question: 'Вопрос',
    answer: 'Ответ',
    cancel: 'Отмена',
    create: 'Создать',
    save: 'Сохранить',
    add: 'Добавить',
    select_deck: 'Выберите колоду, чтобы добавить или отредактировать карточки',
    choose_deck: 'Выберите колоду для учёбы',
    your_stats: 'Ваша статистика',
    learned: 'выучено',
    no_cards: 'Нет карточек',
    deck_done: 'Колода завершена!',
    deck_done_sub: 'Отлично! Вы прошли все карточки.',
    back: '← Вернуться',
    exit: '← Выход',
    know: 'Знаю ✓',
    dont_know: 'Не знаю ✕',
    delete_confirm: 'Удалить навсегда?',
    confirm: 'Подтверждаю',
    create_deck: 'Создать новую колоду',
    deck_name: 'Название колоды',
    deck_desc: 'Описание (опционально)',
    cards: 'карточек',
    deck_complete_btn: 'Колода выучена',
    cards_in_deck: 'Карточки в колоде:',
    learned_count: 'выучено',
    cards_count: 'карточек',
    no_cards: 'Нет карточек',
    no_cards_in_deck: 'В этой колоде нет карточек',
    add_card_btn: '+ Добавить карточку',
    deck_complete_btn: 'Колода выучена',
    edit_card_btn: 'Редактировать',
    delete_card_btn: 'Удалить карточку',
    enter_question_answer: 'Пожалуйста, введите и вопрос, и ответ',
    study: 'Учить',
    account: 'Аккаунт',
    hero_title: 'Учи что угодно быстрее!',
    hero_sub: 'Создавай колоды, учись в своём темпе и отслеживай прогресс — всё в одном месте',
    feature_create: 'Создавай колоды',
    feature_study: 'Учи и повторяй',
    feature_track: 'Следи за прогрессом',
    auth_title: 'Зарегистрируйся, чтобы попробовать!',
    contact: 'Контакты',
    password: 'Пароль',
    email: 'Электронная почта',
    register: 'Зарегистрироваться',
    sign_in: 'Войти',
    continue_google: 'Продолжить с Google',
    password_length: 'Пароль должен быть не менее 6 символов',
    email_already_in_use: 'Этот email уже зарегистрирован. Попробуйте войти',
    something_went_wrong: 'Что-то пошло не так. Пожалуйста, попробуйте снова',
    or: 'или',
    enter_emailAndPassword: 'Пожалуйста, введите ваш email и пароль',
    incorrect_email_or_password: 'Неверный email или пароль',
    valid_emailAndPassword: 'Пожалуйста, введите действительный адрес электронной почты'
  },
  es: {
    my_decks: 'Mis mazos',
    study: 'Estudiar',
    stats: 'Estadísticas',
    your_decks: 'Tus mazos',
    add_deck: '+ Nuevo mazo',
    manage_cards: 'Gestionar tarjetas',
    delete_deck: 'Eliminar mazo',
    add_card: 'Añadir tarjeta',
    question: 'Pregunta',
    answer: 'Respuesta',
    cancel: 'Cancelar',
    create: 'Crear',
    save: 'Guardar',
    add: 'Añadir',
    select_deck: 'Selecciona un mazo para añadir o editar tarjetas',
    choose_deck: 'Elige un mazo para estudiar',
    your_stats: 'Tus estadísticas',
    learned: 'aprendidas',
    no_cards: 'Sin tarjetas',
    deck_done: '¡Mazo completado!',
    deck_done_sub: '¡Genial! Has repasado todas las tarjetas.',
    back: '← Volver',
    exit: '← Salir',
    know: 'Sé ✓',
    dont_know: 'No sé ✕',
    delete_confirm: '¿Eliminar para siempre?',
    confirm: 'Confirmar',
    create_deck: 'Crear nuevo mazo',
    deck_name: 'Nombre del mazo',
    deck_desc: 'Descripción (opcional)',
    cards: 'tarjetas',
    deck_complete_btn: 'Mazo aprendido',
    cards_in_deck: 'Tarjetas en el mazo:',
    learned_count: 'aprendidas',
    cards_count: 'tarjetas',
    no_cards: 'Sin tarjetas',
    no_cards_in_deck: 'No hay tarjetas en este mazo',
    add_card_btn: '+ Añadir tarjeta',
    deck_complete_btn: 'Mazo aprendido',
    edit_card_btn: 'Editar tarjeta',
    delete_card_btn: 'Eliminar tarjeta',
    enter_question_answer: 'Por favor, ingresa tanto la pregunta como la respuesta',
    study: 'Estudiar',
    account: 'Cuenta',
    hero_title: '¡Aprende más rápido!',
    hero_sub: 'Crea mazos, estudia a tu ritmo y sigue tu progreso — todo en un solo lugar',
    feature_create: 'Crear mazos',
    feature_study: 'Estudiar y repetir',
    feature_track: 'Seguir progreso',
    auth_title: '¡Regístrate y pruébalo!',
    contact: 'Contacto',
    password: 'Contraseña',
    email: 'Correo electrónico',
    register: 'Registrarse',
    sign_in: 'Iniciar sesión',
    continue_google: 'Continuar con Google',
    password_length: 'La contraseña debe tener al menos 6 caracteres',
    email_already_in_use: 'Este correo ya está registrado. Intenta iniciar sesión',
    something_went_wrong: 'Algo salió mal. Por favor, intenta de nuevo',
    or: 'o',
    enter_emailAndPassword: 'Por favor, ingresa tu correo electrónico y contraseña',
    valid_emailAndPassword: 'Por favor, ingresa una dirección de correo electrónico válida',
    incorrect_email_or_password: 'Correo electrónico o contraseña incorrectos'
  }
};