export const translations = {
  en: {
    my_decks: 'My Decks',
    study: 'Study',
    stats: 'Statistics',
    your_decks: 'Your Decks',
    add_deck: '+ New Deck',
    manage_cards: 'Manage Cards',
    delete_deck: 'Delete Deck',
    add_card: ' Confirm',
    question: 'Question',
    answer: 'Answer',
    cancel: 'Cancel',
    create: 'Create',
    save: 'Save',
    add: 'Add',
    select_deck: 'Select a deck to add or edit cards',
    choose_deck: 'Choose a deck to study',
    your_stats: 'Your Statistics',
    learned: 'learned',
    no_cards: 'No cards',
    deck_done: 'Deck complete!',
    deck_done_sub: 'Great! You went through all the cards.',
    back: '← Back',
    exit: '← Exit',
    know: 'Know ✓',
    dont_know: "Don't know ✕",
    delete_confirm: 'Delete deck forever?',
    confirm: 'Confirm',
    create_deck: 'Create New Deck',
    deck_name: 'Deck name',
    deck_desc: 'Description (optional)',
    cards: 'cards',
    deck_complete_btn: 'Deck complete',
    cards_in_deck: 'Cards in deck:',
    learned_count: 'learned',
    cards_count: 'cards',
    no_cards: 'No cards',
    no_cards_in_deck: 'No cards in this deck',
    add_card_btn: '+ Add Card',
    deck_complete_btn: 'Deck complete',
    edit_card_btn: 'Edit Card',
    delete_card_btn: 'Delete Card',
    enter_question_answer: 'Please enter both question and answer',
    study: 'Study',
    account: 'Account',
  },
  ru: {
    my_decks: 'Мои колоды',
    study: 'Учёба',
    stats: 'Статистика',
    your_decks: 'Ваши колоды',
    add_deck: '+ Новая колода',
    manage_cards: 'Управление карточками',
    delete_deck: 'Удалить колоду',
    add_card: 'Подтверждаю',
    question: 'Вопрос',
    answer: 'Ответ',
    cancel: 'Отмена',
    create: 'Создать',
    save: 'Сохранить',
    add: 'Добавить',
    select_deck: 'Выберите колоду, чтобы добавить или отредактировать карточки',
    choose_deck: 'Выберите колоду для учёбы',
    your_stats: 'Ваша статистика',
    learned: 'выучено',
    no_cards: 'Нет карточек',
    deck_done: 'Колода завершена!',
    deck_done_sub: 'Отлично! Вы прошли все карточки.',
    back: '← Вернуться',
    exit: '← Выход',
    know: 'Знаю ✓',
    dont_know: 'Не знаю ✕',
    delete_confirm: 'Удалить колоду навсегда?',
    confirm: 'Подтверждаю',
    create_deck: 'Создать новую колоду',
    deck_name: 'Название колоды',
    deck_desc: 'Описание (опционально)',
    cards: 'карточек',
    deck_complete_btn: 'Колода выучена',
    cards_in_deck: 'Карточки в колоде:',
    learned_count: 'выучено',
    cards_count: 'карточек',
    no_cards: 'Нет карточек',
    no_cards_in_deck: 'В этой колоде нет карточек',
    add_card_btn: '+ Добавить карточку',
    deck_complete_btn: 'Колода выучена',
    edit_card_btn: 'Редактировать',
    delete_card_btn: 'Удалить карточку',
    enter_question_answer: 'Пожалуйста, введите и вопрос, и ответ',
    study: 'Учить',
    account: 'Аккаунт',
  },
  es: {
    my_decks: 'Mis mazos',
    study: 'Estudiar',
    stats: 'Estadísticas',
    your_decks: 'Tus mazos',
    add_deck: '+ Nuevo mazo',
    manage_cards: 'Gestionar tarjetas',
    delete_deck: 'Eliminar mazo',
    add_card: ' Confirmar',
    question: 'Pregunta',
    answer: 'Respuesta',
    cancel: 'Cancelar',
    create: 'Crear',
    save: 'Guardar',
    add: 'Añadir',
    select_deck: 'Selecciona un mazo para añadir o editar tarjetas',
    choose_deck: 'Elige un mazo para estudiar',
    your_stats: 'Tus estadísticas',
    learned: 'aprendidas',
    no_cards: 'Sin tarjetas',
    deck_done: '¡Mazo completado!',
    deck_done_sub: '¡Genial! Has repasado todas las tarjetas.',
    back: '← Volver',
    exit: '← Salir',
    know: 'Sé ✓',
    dont_know: 'No sé ✕',
    delete_confirm: '¿Eliminar el mazo para siempre?',
    confirm: 'Confirmar',
    create_deck: 'Crear nuevo mazo',
    deck_name: 'Nombre del mazo',
    deck_desc: 'Descripción (opcional)',
    cards: 'tarjetas',
    deck_complete_btn: 'Mazo aprendido',
    cards_in_deck: 'Tarjetas en el mazo:',
    learned_count: 'aprendidas',
    cards_count: 'tarjetas',
    no_cards: 'Sin tarjetas',
    no_cards_in_deck: 'No hay tarjetas en este mazo',
    add_card_btn: '+ Añadir tarjeta',
    deck_complete_btn: 'Mazo aprendido',
    edit_card_btn: 'Editar tarjeta',
    delete_card_btn: 'Eliminar tarjeta',
    enter_question_answer: 'Por favor, ingresa tanto la pregunta como la respuesta',
    study: 'Estudiar',
    account: 'Cuenta',
  }
};